services:
  oracle:
    image: gvenzl/oracle-free
    container_name: oracle
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PASSWORD=oracle
    volumes:
      - ./oradata:/opt/oracle/oradata
