SET SQLBLANKLINES ON;
SET DEFINE OFF;
SET ECHO ON;
SPOOL /tmp/sql_log.txt;
PROMPT Cleaning up existing tables...
@cleanup.sql
PROMPT Running create_table.sql...
@create_table.sql
PROMPT Running 03a_insertions_base.sql...
@03a_insertions_base.sql
PROMPT Running 03b_insertions_patient.sql...
@03b_insertions_patient.sql
PROMPT Running 03c_insertions_soins_partie1.sql...
@03c_insertions_soins_partie1.sql
PROMPT Running 03c_insertions_soins_partie2.sql...
@03c_insertions_soins_partie2.sql
PROMPT Running 03d_etat_buccal.sql...
@03d_etat_buccal.sql
PROMPT Running index.sql...
@index.sql
SPOOL OFF;
EXIT;
